---
- name: Ensure that the borg directory exists
  file:
    path: "{{ borg_binary | dirname }}"
    state: directory
    recurse: true

- name: Fetch borg binary
  get_url:
    url: "{{ borg_url }}"
    dest: "{{ borg_binary }}"
    mode: "0755"
    checksum: "{{ borg_checksum }}"

- name: Create a borg unversioned symlink
  file:
    src: "{{ borg_binary }}"
    dest: "{{ borg_binary_symlink }}"
    state: link

