- name: Create repository for {{ item.name }}
  file:
    path: "{{ borg_repo_root }}/{{ item.name }}"
    state: directory
    mode: 0700

- name: Ensure that the ssh key is present
  lineinfile:
    path: "{{ ansible_env.HOME }}/.ssh/authorized_keys"
    regexp: "^command.*{{ borg_repo_root }}/{{ item.name }}"
    line: "command=\"{{ borg_binary_symlink }} serve --restrict-to-path {{ borg_repo_root }}/{{ item.name }}\" {{ item.ssh_public_key }}"

